### ISSUE TITLE
borderRadius property regression?

### ISSUE THREAD

**Issue by jh3y** [styled-components/css-to-react-native#11] opened 2016-11-24 05:36 UTC
I had opened up an issue over on `styled-components` [here](https://github.com/styled-components/styled-components/issues/248) about the `borderRadius` property on native.

It seems going from version `1.0.11` to `1.1.1` in `styled-components` regressed how `borderRadius` would work.

`borderTopLeftRadius` etc. seemingly have no effect when developing for native from what I can tell in the simulator and what works is simply using `borderRadius`.

After having a dive into the source, I think this just requires a slight change to the grammar file to only output `borderRadius`.

I'll submit a PR for this.

@jh3y

**Comment by jacobp100** [comment] 2016-11-24 08:02
I'll have to test this. RN claims to support this. https://facebook.github.io/react-native/docs/view.html#style

**Comment by mxstbr** [comment] 2016-11-24 08:16
I don't quite understand what the issue here is, what should be happening that isn't happening?

**Comment by jacobp100** [comment] 2016-11-24 10:23
I’m not able to reproduce this on 0.38. You are correct in how `border-radius` splats into `borter-{top,bottom}-{left,right}-radius`, but that does seem to work.

![screen shot 2016-11-24 at 10 08 22](https://cloud.githubusercontent.com/assets/7275322/20594744/477cb62a-b22f-11e6-8402-e5eafc4793c5.png)
![screen shot 2016-11-24 at 10 17 41](https://cloud.githubusercontent.com/assets/7275322/20594747/47a11cfe-b22f-11e6-8ada-54b28383080f.png)

**Comment by jh3y** [comment] 2016-11-24 12:38
I've just tested this out again using `react-native@0.38` and `styled-components@1.1.1`, same issue.

In the simulator, could you inspect that with the inspector and see what style properties are given?

What is `cssta(View)`? I'm using `styled.Image` to get this issue.

@jh3y

**Comment by jacobp100** [comment] 2016-11-24 14:16
Got you. It’s fixed in #13.

**Comment by jh3y** [comment] 2016-11-24 14:21
I don't think it can be fixed here can it? I think this is potentially a `react-native` issue.

`borderTopLeftRadius` etc. work differently with `Image` to how they do with `View`.

It would be a nice to have for now if only supplying one value, it only output `borderRadius` though 😎 

@jh3y

**Comment by jacobp100** [comment] 2016-11-24 14:30
Can you not wrap the image in a View, and use `overflow: hidden`?

**Comment by jh3y** [comment] 2016-11-24 14:33
Yeah I mentioned that as a solution above but then that means refactoring every instance of an `Image` component that is rounded to be wrapped by a `View` which isn't ideal overhead if it works how I intend when using `styled-components@1.0.11` 😕

**Comment by jacobp100** [comment] 2016-11-24 14:38
I’m thinking, special casing is going to be hard:

```js
const StyledImage = styled(Image)`...`; // This is hard enough to work out that we need to special case
const SuperSpecialStyledImage = styled(StyledImage)`...` // This is almost impossible
```

Maybe we need to turn off this shorthand for the time being. @mxstbr

**Comment by mxstbr** [comment] 2016-11-24 16:52
Let's turn it off then!

**Comment by mxstbr** [comment] 2016-11-24 16:52
But that's a major version release again, ugh

**Comment by jacobp100** [comment] 2016-11-24 17:06
That's true. Maybe we just document the behaviour?

**Comment by jacobp100** [comment] 2016-11-24 17:08
Although I suppose this was a breaking change in the first place? I believe semver says we should revert the breaking change.

**Comment by mxstbr** [comment] 2016-11-24 17:13
Oh if it was a breaking change in the first place let's push this as a patch. Would you mind doing that?

**Comment by jh3y** [comment] 2016-11-24 17:49
Happy to help if required :smile:

**Comment by jacobp100** [comment] 2016-11-24 18:21
Over here! https://github.com/styled-components/styled-components/compare/fix-border-radius?expand=1

**Comment by jacobp100** [comment] 2019-04-12 11:05
Looks like we could turn this off soon

https://github.com/facebook/react-native/commit/66a294032a41f489ef5407975b2a5276df825ceb

There's a few other cases that'll get fixed too

**Comment by magik-chorne** [comment] 2020-01-09 21:39
Poking on this one @jacobp100

**Comment by jacobp100** [comment] 2020-01-10 07:28
Has anyone confirmed this works now? And from what version it works

**Comment by jacobp100** [comment] 2020-01-20 20:53
Also, the change to re-enable these has to happen in styled-components. We take a blacklist of properties, and the border-radius is passed in there in SC

Once SC removes this, we'll remove the code around blacklisting here too, since it will no longer be needed

**Comment by jacobp100** [comment] 2020-01-20 21:19
https://github.com/styled-components/styled-components/pull/2976

**Comment by RemyMachado** [comment] 2021-08-23 13:16
5 years later, there still isn't a solution to this problem?

**Comment by jacobp100** [comment] 2023-02-14 11:43
I'm closing this because it's been years since this was an issue

**Closed by jacobp100** 2023-02-14 11:43 UTC
