### ISSUE TITLE
Background issue with React native 0.61-rc3

### ISSUE THREAD

**Issue by ScreamZ** [styled-components/css-to-react-native#117] opened 2019-09-23 08:35 UTC
Hello

After investigating with @Trobyss we found an issue with styled-components after migrating on 0.61-rc3 to test on ANDROID.

```
ANDROID ONLY
"react": "16.9.0",
"react-native": "0.61.0-rc.3",
"styled-components": "^4.3.2"
```

You can freely switch between `Bug` and `BuggingView` to see the difference.
The text is correctly displaying above the background in absolute, but not the background of the text container.

Without styled-components, this works.

```tsx
import React from "react";
import { Text, View } from "react-native";
import styled from "styled-components/native";

const Bug = () => {
  return (
    <View style={{ flex: 1 }}>
      <BuggingView />
      <PageWrapper>
        <Text>
          This should appear above backgroundThis should appear above background This should appear above background This should appear
          above above background This should appear above background This should appear above background This should appear above background
          This This should appear above background This should appear above background This should appear above background This should
          appear above background This should appear above background This should appear above background This should appear above
          background This should appear above background This should appear above background This should appear above background This should
          appear above background This should appear above background This should appear above background This should appear above
          background This should appear above background This should appear above background This should appear above background This should
          appear above background This should appear above background This should appear above background This should appear above
          background This should appear above background
        </Text>
      </PageWrapper>
    </View>
  );
};

const BuggingView = styled.View`
  height: 200;
  position: absolute;
  background-color: blue;
  top: 0;
  right: 0;
  left: 0;
`;
const PageWrapper = styled.View`
  background-color: red;
  padding: 20px; 
  border-radius: 8px;
  flex: 1;
  margin: 20px;
`;

const NotBug = () => (
  <View style={{ flex: 1 }}>
    <View style={{ height: 200, backgroundColor: 'blue', position: "absolute", top: 0, right: 0, left: 0 }} />
    <View style={{ backgroundColor: "red", padding: 20, flex: 1, margin: 20 }}>
      <Text>
        This should appear above backgroundThis should appear above background This should appear above background This should appear above
        above background This should appear above background This should appear above background This should appear above background This
        This should appear above background This should appear above background This should appear above background This should appear above
        background This should appear above background This should appear above background This should appear above background This should
        appear above background This should appear above background This should appear above background This should appear above background
        This should appear above background This should appear above background This should appear above background This should appear above
        background This should appear above background This should appear above background This should appear above background This should
        appear above background This should appear above background This should appear above background This should appear above background
      </Text>
    </View>
  </View>
);

export default Bug;
```

Any idea what would cause that ? as you can see this works with latest expo version : https://snack.expo.io/@afigueiredo/1fe053

Best regards

**Comment by jacobp100** [comment] 2019-09-23 08:40
When you write `flex: 1` in css-to-react-native, it expands to `flex-grow: 1; flex-shrink: 1; flex-basis: 0` to match CSS.

The `flex` property in react-native is kinda legacy, in that it differs from the web standards. But their flex-grow, shrink and basis properties do match the web standards

**Comment by Trobyss** [comment] 2019-09-23 09:59
Hi ! I attach a screen

![65132239-ec404180-da00-11e9-9503-6d685ad68fa7](https://user-images.githubusercontent.com/43353685/65416962-46724580-ddf9-11e9-9c9d-e3ece4f51bdc.png)

**Comment by jacobp100** [comment] 2019-09-23 10:32
I'll need to see both screenshots 😄

Did changing flex not work? Try playing around with that a bit. I'm not totally sure what you're trying to do, so I can't really give pointers here

**Comment by Trobyss** [comment] 2019-09-23 13:58
So :

**This doesn't work : (text is above but red is behind blue)**
![Capture d’écran 2019-09-23 à 15 49 34](https://user-images.githubusercontent.com/43353685/65431677-28690d00-de1a-11e9-9d88-776455b404cd.png)

```tsx
import React from "react";
import { Text, SafeAreaView } from "react-native";
import styled from "styled-components/native";

const Venue: React.FC<{}> = () => (
  <SafeAreaView style={{ flexGrow: 1 }}>
    <BuggingView />
    <PageWrapper>
      <Text>
        This should appear above backgroundThis should appear above background This should appear above background This should appear
        above above background This should appear above background This should appear above background This should appear above background
        This This should appear above background This should appear above background This should appear above background This should
        appear above background This should appear above background This should appear above background This should appear above
        background This should appear above background This should appear above background This should appear above background This should
        appear above background This should appear above background This should appear above background This should appear above
        background This should appear above background This should appear above background This should appear above background This should
        appear above background This should appear above background This should appear above background This should appear above
        background This should appear above background
        </Text>
    </PageWrapper>
  </SafeAreaView >
);
  const BuggingView = styled.View`
    height: 200;
    position: absolute;
    background-color: blue;
    top: 0;
    right: 0;
    left: 0;
  `;
  const PageWrapper = styled.View`
    background-color: red;
    padding: 20px; 
    border-radius: 8px;
    flex-grow: 1;
    flex-shrink: 1;
    flex-basis: 0;
    margin: 20px;
  `;
```

But the exact same code without styled :

![Capture d’écran 2019-09-23 à 15 55 27](https://user-images.githubusercontent.com/43353685/65431987-af1dea00-de1a-11e9-837a-d6ad399c4ae8.png)

```tsx
import React from "react";
import { Text, SafeAreaView, View } from "react-native";

const Venue: React.FC<{}> = () => (
  <SafeAreaView style={{ flexGrow: 1 }}>
    <View style={{ height: 200, backgroundColor: 'blue', position: "absolute", top: 0, right: 0, left: 0 }} />
    <View style={{ backgroundColor: "red", padding: 20, flexGrow: 1, flexShrink: 1, flexBasis: 0, margin: 20 }}>
      <Text>
        This should appear above backgroundThis should appear above background This should appear above background This should appear above
        above background This should appear above background This should appear above background This should appear above background This
        This should appear above background This should appear above background This should appear above background This should appear above
        background This should appear above background This should appear above background This should appear above background This should
        appear above background This should appear above background This should appear above background This should appear above background
        This should appear above background This should appear above background This should appear above background This should appear above
        background This should appear above background This should appear above background This should appear above background This should
        appear above background This should appear above background This should appear above background This should appear above background
      </Text>
    </View>
  </SafeAreaView >
);
```
As u can see, **it's not related** to flex box implementation.
Before 0.61-rc3 this work.

Any idea ?

Trobyss'

**Comment by jacobp100** [comment] 2019-09-23 14:04
Thanks for those screenshots. So am I right in thinking the layout is correct, but the order is wrong. Does adding some z-indices fix it?

**Comment by Trobyss** [comment] 2019-09-23 14:34
Nothing at all for the background :(

**Comment by kristerkari** [comment] 2019-09-25 10:00
@jacobp100 

I tried to update the app I'm working on to 0.61.0, and I'm seeing the same thing: the styles are messed up on Android, but not iOS. 

I'm using CSS modules instead of styled components.

**Comment by kristerkari** [comment] 2019-09-25 10:18
I found this from https://github.com/facebook/react-native/issues/26544

> if view has a borderRadius other than undefined, then when switching to another screen, the view with borderRadius is rendered under all other views, even if you specify zIndex. Until you reload, all views on all screens with borderRadius (including the root) will be broken. 

Looks like a serious React Native bug

**Comment by jacobp100** [comment] 2019-09-25 10:21
Thanks for finding that — @Trobyss could you see if removing the border radius fixes the issue?

**Comment by kristerkari** [comment] 2019-09-25 10:48
I created a new 0.61 and I'm trying to the examples from @Trobyss, but I'm not seeing the bug on Android using those examples.

**Comment by marcorm** [comment] 2019-09-25 10:52
> I created a new 0.61 project and I'm trying to the examples from @Trobyss, but I'm not seeing the bug on Android using those examples.

@kristerkari i don't know if it helps, but i'm facing strange behaviour only on **Android API Level 26** 
I think also this [bug](https://github.com/callstack/react-native-paper/issues/1341) is related:

**Comment by kristerkari** [comment] 2019-09-25 11:03
> i don't know if it helps, but i'm facing strange behaviour only on **Android API Level 26**

I tried on two emulators with API 26, but still could not reproduce the bug with the examples from this thread. Maybe someone else could try to do the same thing and see if the bug can be reproduced?

I know that there is something broken with 0.61 because I saw styles being broken on Android in the other project that I updated from 0.60.

**Comment by ScreamZ** [comment] 2019-09-25 15:46
Removing border-radius seems to fix the issue for this example 👍 
```tsx

const Bug = () => {
  return (
    <View style={{ flex: 1 }}>
      <BuggingView />
      <PageWrapper>
        <Text>
          This should appear above backgroundThis should appear above background This should appear above background This should appear
          above above background This should appear above background This should appear above background This should appear above background
          This This should appear above background This should appear above background This should appear above background This should
          appear above background This should appear above background This should appear above background This should appear above
          background This should appear above background This should appear above background This should appear above background This should
          appear above background This should appear above background This should appear above background This should appear above
          background This should appear above background This should appear above background This should appear above background This should
          appear above background This should appear above background This should appear above background This should appear above
          background This should appear above background
        </Text>
      </PageWrapper>
    </View>
  );
};

const BuggingView = styled.View`
  height: 200;
  position: absolute;
  background-color: blue;
  top: 0;
  right: 0;
  left: 0;
`;
const PageWrapper = styled.View`
  background-color: red;
  padding: 20px;
  /* border-radius: 8px; */
  flex: 1;
  margin: 20px;
`;
```

**Comment by ScreamZ** [comment] 2019-09-30 13:23
https://github.com/react-native-community/releases/issues/146#issuecomment-536548800

**Comment by jacobp100** [comment] 2019-09-30 13:37
I'm going to close this issue, but you're free to continue the discussion here if you wish

**Closed by jacobp100** 2019-09-30 13:37 UTC
